
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:db_charon:fJsnHnX3wrisYdjS@tcp(121.54.189.30:3306)/db_charon?loc=Local&parseTime=true&charset=utf8mb4"
        descriptionTag: true
        removePrefix: tb_
        jsonCase: "CamelLower"
        gJsonSupport: true


  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app