// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"charon/internal/dao/internal"
)

// clusterDao is the data access object for the table tb_cluster.
// You can define custom methods on it to extend its functionality as needed.
type clusterDao struct {
	*internal.ClusterDao
}

var (
	// Cluster is a globally accessible object for table tb_cluster operations.
	Cluster = clusterDao{internal.NewClusterDao()}
)

// Add your custom methods and functionality below.
