// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"charon/internal/dao/internal"
)

// serviceContainersDao is the data access object for the table tb_service_containers.
// You can define custom methods on it to extend its functionality as needed.
type serviceContainersDao struct {
	*internal.ServiceContainersDao
}

var (
	// ServiceContainers is a globally accessible object for table tb_service_containers operations.
	ServiceContainers = serviceContainersDao{internal.NewServiceContainersDao()}
)

// Add your custom methods and functionality below.
