// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"charon/internal/dao/internal"
)

// serviceBaseDao is the data access object for the table tb_service_base.
// You can define custom methods on it to extend its functionality as needed.
type serviceBaseDao struct {
	*internal.ServiceBaseDao
}

var (
	// ServiceBase is a globally accessible object for table tb_service_base operations.
	ServiceBase = serviceBaseDao{internal.NewServiceBaseDao()}
)

// Add your custom methods and functionality below.
